name: Update Version

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

permissions:
  contents: write # Ensure write access to the repository's contents

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Fetch the full history to allow version bumping

      # Step 2: Bump the version (Patch, Minor, or Major)
      - name: Bump Version
        run: |
          npm version patch --no-git-tag-version  # Bumps the patch version

      # Step 3: Commit the updated version back to the repository
      - name: Commit Updated Version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package.json
          git commit -m "Bump version to $(node -p "require('./package.json').version")"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
